yuki.mapper.*:
  type: config_entity
  label: 'Mapper config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    plugin:
      type: string
      label: 'Plugin ID'
    data:
      type: string
      label: 'Data'
    weight:
      type: integer
      label: 'Weight'